-- Deploy theridiid:create_resources_table to pg

BEGIN;

CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id uuid NOT NULL,
    title text NOT NULL,
    contents text NOT NULL,
    mime text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMIT;
