-- Deploy theridiid:create_tags_table to pg

BEGIN;

CREATE TABLE tags (
    id bigint generated by default as identity primary key,
    tag_id text NOT NULL,
    tag text NOT NULL,
    created_time timestamp default current_timestamp
);

COMMIT;
