-- Deploy theridiid:create_notes_table to pg

BEGIN;

CREATE TABLE notes (
    id bigint generated by default as identity primary key,
    note_id text NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    tags text [],
    parent_id text NOT NULL,
    order_id bigint NULL,
    is_todo boolean NOT NULL,
    todo_due boolean NOT NULL,
    todo_completed boolean NOT NULL,
    link_content text NULL,
    link_length bigint NULL,
    link_excerpt text NULL,
    link_by_line text NULL,
    created_time bigint NOT NULL
);

COMMIT;
