-- Deploy theridiid:create_subscribers_table to pg

BEGIN;

CREATE TABLE subscribers (
    id bigint generated by default as identity primary key,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    topics text [],
    frequency text NOT NULL,
    created_at timestamp default current_timestamp
);

COMMIT;
