-- Deploy theridiid:create_folders_table to pg

BEGIN;

CREATE TABLE folders (
    id bigint generated by default as identity primary key,
    folder_id text NOT NULL,
    title text NOT NULL,
    icon text NOT NULL,
    user_updated_time bigint NOT NULL,
    created_time timestamp default current_timestamp
);

COMMIT;
